server:
  port: 8767

eureka:
  client:

    serviceUrl:
      defaultZone: http://192.168.0.105:8761/eureka/

spring:
  application:
    name: service-zuul

zuul:
  routes:
    service:
      path: /out/**
      serviceId: service-feign